FROM golang:1.21-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o payments-service ./cmd/payments-service

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/payments-service .

EXPOSE 4003
ENTRYPOINT ["./payments-service"]
